### ISSUE TITLE
arrays of ndim > 2 incorrectly assigned to

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/nervanagpu#11]
a = ng.ones((2, 2, 2))
    a *= 2

produces:

    array([[[ 2.,  1.],
            [ 2.,  1.]],
    
           [[ 2.,  1.],
            [ 2.,  1.]]], dtype=float16)

**Comment by scott-gray** [comment]
Fixing that particular operation is easy enough (I already have in fact), but more broadly supporting greater than 2 dimensions has been on my mind for a while.  What other kind of support would you have a use for?

**Comment by oleg-trott** [comment]
Thanks for the quick fix! I'll create separate issues for other problems if I see them. I noticed that `None` doesn't work as an index, and `-1` doesn't work in `reshape`, but these can of course be worked around.
