### ISSUE TITLE
1D slices fail

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/nervanagpu#12]
a = ng.ones((2, 2))
    b = ng.zeros((2,))
    a[:, 0] = b

causes "tuple index out of range" in float_ew.py:736

**Comment by apark263** [comment]
Did you try b = ng.zeros((2,1))?

Is this because you specifically want to use 1-d notation?

**Comment by oleg-trott** [comment]
I'm not sure what you mean:

    a = ng.ones((2, 2))
    b = ng.zeros((2, 1))

This gives the same error:    

    a[:, 0] = b

and this triggers "invalid argument":

    a[:] = b

**Comment by apark263** [comment]
interesting... it does seem like a bug.

incidentally,

a[:, :1] = b

seems to work...

**Comment by oleg-trott** [comment]
By the way, the same line trips up 0D and 1D arrays in *e.g.*

    a1 = ng.ones((2,))
    a1 *= 2

and

    a0 = ng.ones(())
    a0 *= 2

**Comment by scott-gray** [comment]
Ok, those issues are now fixed.  Keep in mind that the current elementwise engine is designed to work with 2d shapes.  When tensors or views are created, the most efficient ew dims are automatically found and used for subsequent simple (not reduction or broadcast) ew ops.  If you want to do reduction or broadcast with non-2d shapes, you'll need to reshape to a 2d dim first.  At some point I'll like to build in full numpy support for non-2d shapes but have been working on other things for the time being.  I think the next big thing I want to implement for ew is fancy indexing and take().

**Comment by oleg-trott** [comment]
It's running now, but not like in NumPy:

    a = ng.ones((2, 2))
    b = ng.zeros((2,))
    a[:, 0] = b

produces:

    array([[ 0.,  0.],
           [ 1.,  1.]], dtype=float16)

while in NumPy, it's

    array([[ 0.,  1.],
           [ 0.,  1.]])

(`a[:, :1] = b` seems to work correctly though)

**Comment by oleg-trott** [comment]
This is probably related: the example on the front page appears to work differently from NumPy:

    In [311]: a = ng.ones((2, 2))
    In [312]: c = ng.ones((2, 2))
    In [313]: c[:] = ng.mean(ng.square(a - ng.mean(a, axis=1)), axis=1)
    In [314]: c.get()
    Out[314]: 
    array([[ 0.,  1.],
           [ 0.,  1.]], dtype=float16)

While with NumPy, we have:

    In [315]: a = np.ones((2, 2))
    In [316]: c = np.ones((2, 2))
    In [317]: c[:] = np.mean(np.square(a - np.mean(a, axis=1)), axis=1)
    In [318]: c
    Out[318]: 
    array([[ 0.,  0.],
           [ 0.,  0.]])

**Comment by scott-gray** [comment]
That's actually a known issue I haven't gotten to yet.  I do shape compatibility checking on all input tensors, but not the output tensor.  The result of a reduction along axis=1 is shape (2,1) which you're assigning to a (2,2) shape.  Looks like numpy broadcasts the assignment there.  I suppose I should do the same.  

I'll look into your other bug in a bit, but 1d tensor support is going to remain kind of a big hack until I can spend some real time on it.  I'd stick with (x,1) or (1,x) shapes for now.  The reduction ops all have an implicit keepdims=True option set for this reason.

**Comment by oleg-trott** [comment]
Looks like this has been fixed.
