### ISSUE TITLE
strided sizes calculated incorrectly

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/nervanagpu#13]
a = ng.zeros((10, 10))
    b = ng.ones((5, 5))
    a[::2, ::2] = b  # OK
    a[1::2, ::2] = b #  FAILS

This also happens for `ndim  = 3`

**Comment by scott-gray** [comment]
That was a good find.  It was an old bug from the original pycuda gpuarray code.  Fixed that in the latest commit (along with a bunch of rounding changes).

**Comment by oleg-trott** [comment]
By the way, you don't have to use `int(ceil(float(x)/y))`. Grep shows that it's in quite a few places in the code:

    ./nervanagpu/float_ew.py:                        gridY = int(ceil(max_shape[1] / 256.))
    ./nervanagpu/nervanagpu.py:                new_shape.append(int(ceil(float(stop-start)/idx_stride)))
    ./nervanagpu/layers.py:        M = int(ceil(float(D - T + 1 + 2*pad_d) / str_d))
    ./nervanagpu/layers.py:        P = int(ceil(float(H - R + 1 + 2*pad_h) / str_h))
    ./nervanagpu/layers.py:        Q = int(ceil(float(W - S + 1 + 2*pad_w) / str_w))
    ./nervanagpu/layers.py:            self.overlap =  ceil(float(J)/str_j) * \
    ./nervanagpu/layers.py:                            ceil(float(T)/str_d) * \
    ./nervanagpu/layers.py:                            ceil(float(R)/str_h) * \
    ./nervanagpu/layers.py:                            ceil(float(S)/str_w)
    ./nervanagpu/layers.py:        K = int(ceil(float(C - J + 1 + 2*pad_j) / str_j))
    ./nervanagpu/layers.py:        M = int(ceil(float(D - T + 1 + 2*pad_d) / str_d))
    ./nervanagpu/layers.py:        P = int(ceil(float(H - R + 1 + 2*pad_h) / str_h))
    ./nervanagpu/layers.py:        Q = int(ceil(float(W - S + 1 + 2*pad_w) / str_w))

`ceil_div` is 3x faster and has unlimited validity range (for y > 0 and x >= 0) : 

    def ceil_div(x, y): return (x + y - 1) // y
    def float_div(x, y): return int(ceil(float(x)/y))

**Comment by scott-gray** [comment]
Thanks for the tip.. I knew there was a better way, was just too lazy to look it up.  It looks like this might even be slightly faster still:
```def ceil_div(x, y): return -(-x // y)```
