### ISSUE TITLE
"not" has surprising behavior

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/nervanagpu#14]
In [347]: a = ng.ones((1, 1))

    In [348]: b = ng.zeros_like(a)

    In [349]: b[:] = (a > 2)

    In [350]: b.get()
    Out[350]: array([[ 0.]], dtype=float16)

    In [351]: b[:] = not (a > 2)

    In [352]: b.get()
    Out[352]: array([[ 0.]], dtype=float16)

    In [353]: b[:] = (1 - (a > 2))

    In [354]: b.get()
    Out[354]: array([[ 1.]], dtype=float16)

**Comment by scott-gray** [comment]
It's apparently not possible to override the "and", "or" and "not" operators in python (they're considered control flow like "if").  The comparison operators return 1.0 or 0.0 so you can always just subtract the result from 1 to achieve negation.

**Comment by oleg-trott** [comment]
The class can define `__nonzero__` and make it raise `ValueError`, as Numpy appears to be doing.

**Comment by scott-gray** [comment]
Done.  Also added ceil_div in performance critical code.

**Comment by oleg-trott** [comment]
It appears pytools includes `div_ceil`. If it's really performance-critical, you may want to manually inline it:

    In [1]: from pytools import div_ceil

    In [2]: %timeit div_ceil(100, 3)
    10000000 loops, best of 3: 150 ns per loop

    In [3]: %timeit (-((-100)//3))
    100000000 loops, best of 3: 15.2 ns per loop
