### ISSUE TITLE
Make test fails with illegal memory access (cuMemFree)

### ISSUE THREAD

**Issue by revilokeb** [NervanaSystems/nervanagpu#16]
When running make test I get the following memory acces failure:

make test
Running unit tests...
nosetests -a '!slow' ""   nervanagpu
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
EPyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered

======================================================================
ERROR: nervanagpu.tests.test_tensor.TestTensor.test_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/revilokeb/nervanagpu/nervanagpu/tests/test_tensor.py", line 77, in test_math
    self.compare_helper('*', randA, randB, dtype)
  File "/home/revilokeb/nervanagpu/nervanagpu/tests/test_tensor.py", line 57, in compare_helper
    assert_tensor_near_equal(numpy_result, nervanaGPU_result, 1e-5)
  File "/home/revilokeb/nervanagpu/nervanagpu/util/testing.py", line 43, in assert_tensor_near_equal
    desired = desired.asnumpyarray()
  File "/home/revilokeb/nervanagpu/nervanagpu/nervanagpu.py", line 210, in asnumpyarray
    return self.get()
  File "/home/revilokeb/nervanagpu/nervanagpu/nervanagpu.py", line 203, in get
    drv.memcpy_dtoh_async(ary, self.gpudata, stream)
LogicError: cuMemcpyDtoHAsync failed: an illegal memory access was encountered

----------------------------------------------------------------------
Ran 1 test in 0.637s

FAILED (errors=1)
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
make: *** [test] Error 1

--------------------------------------------------------------------
--------------------------------------------------------------------

Background info:
--------------------------------------------------------------------
OS:  Ubuntu 14.04.2 LTS
2 Titan X with CUDA 7 installed (other DL libraries such as caffe do work)
pip show pycuda: Version: 2015.1.2
pip show pytools: 2014.3.5

--------------------------------------------------------------------
~$ sudo cpanm git://github.com/NervanaSystems/maxas.git
...
Building and testing MaxAs-MaxAs-1.02 ... OK
Successfully installed MaxAs-MaxAs-1.02

---------------------------------------------------------------------
~/nervanagpu$ make kernels
...(mostly inconspicous except for a few bank conflicts such as the following)
Kernel: hsgemm_nt_vec_32x128, Instructions: 906, Register Count: 128, Bank Conflicts: 0, Reuse: 43.4% (807/1861)
building kernel: hpool_max...
CONFLICT at 0x0090 (R8,R12): XMAD R16, R11, R8, R12; (XMAD iOut, N, q, tid;)
CONFLICT at 0x05b0 (R24,R28): FSETP.GT.AND P0, PT, R24, R28, P0; (FSETP.GT.AND P0, PT, load0, max, P0;)
Modified hpool_max RegCnt: 5 => 63
Modified hpool_max BarCnt: 0 => 1
Modified hpool_max Size: 128 => 1856
Kernel: hpool_max, Instructions: 167, Register Count: 63, Bank Conflicts: 2, Reuse: 20.9% (38/182)
building kernel: spool_max...
CONFLICT at 0x0090 (R8,R12): XMAD R16, R11, R8, R12; (XMAD iOut, N, q, tid;)
CONFLICT at 0x0588 (R24,R28): FSETP.GT.AND P0, PT, R24, R28, P0; (FSETP.GT.AND P0, PT, load0, max, P0;)
Modified spool_max RegCnt: 5 => 63
Modified spool_max BarCnt: 0 => 1
Modified spool_max Size: 128 => 1728

---------------------------------------------------------
!!need to sudo it!!
~/nervanagpu$ sudo make python
removing existing nervanagpu python bindings...
Uninstalling nervanagpu:
  Successfully uninstalled nervanagpu
installing nervanagpu python bindings...
Unpacking /home/revilokeb/nervanagpu
  Running setup.py (path:/tmp/pip-Mu4Rxi-build/setup.py) egg_info for package from file:///home/revilokeb/nervanagpu

    no previously-included directories found matching 'doc/build'
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): pycuda>=2015.1 in /usr/local/lib/python2.7/dist-packages/pycuda-2015.1.2-py2.7-linux-x86_64.egg (from nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): pytools in /usr/local/lib/python2.7/dist-packages/pytools-2014.3.5-py2.7.egg (from nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in /usr/local/lib/python2.7/dist-packages/pytest-2.7.2-py2.7.egg (from pycuda>=2015.1->nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in /usr/lib/python2.7/dist-packages (from pycuda>=2015.1->nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages/appdirs-1.4.0-py2.7.egg (from pycuda>=2015.1->nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pytools->nervanagpu==0.3.3)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in /usr/local/lib/python2.7/dist-packages/py-1.4.30-py2.7.egg (from pytest>=2->pycuda>=2015.1->nervanagpu==0.3.3)
Installing collected packages: nervanagpu
  Running setup.py install for nervanagpu
    make[1]: Entering directory `/tmp/pip-Mu4Rxi-build'
    make[1]: Nothing to be done for `kernels'.
    make[1]: Leaving directory `/tmp/pip-Mu4Rxi-build'

    no previously-included directories found matching 'doc/build'
Successfully installed nervanagpu
Cleaning up...

----------------------------------------------------
make test is then failing as described above. Any ideas what could be done?

**Comment by apark263** [comment]
Hi,

I'm really puzzled as to why this isn't working -- your version of
nervanagpu and all required packages are exactly as they should be, but I'm
unable to replicate the error on my system.

moreover, it's strange that the first two operator tests seem to be ok and
it's failing on '*'.

a couple of possibilities:  have you modified anything in the code? are you
running anything concurrently (not that it should fail because of this)? do
you have anything special in your PYTHONPATH?

Could you try doing a standalone test where you instantiate a nervanagpu
backend, allocate device buffers and then copy back to host?

from nervanagpu import NervanaGPU
import numpy as np
import pycuda.autoinit

a = ng.array(np.random.uniform(-1, 1, 25).reshape((5,5)).astype(np.float32))
print a.get()

**Comment by apark263** [comment]
Hi,

I'm really puzzled as to why this isn't working -- your version of
nervanagpu and all required packages are exactly as they should be, but I'm
unable to replicate the error on my system.

moreover, it's strange that the first two operator tests seem to be ok and
it's failing on '*'.

a couple of possibilities:  have you modified anything in the code? are you
running anything concurrently (not that it should fail because of this)? do
you have anything special in your PYTHONPATH?

Could you try doing a standalone test where you instantiate a nervanagpu
backend, allocate device buffers and then copy back to host?

```
from nervanagpu import NervanaGPU
import numpy as np
import pycuda.autoinit

a = ng.array(np.random.uniform(-1, 1, 25).reshape((5,5)).astype(np.float32))
print a.get()
```

**Comment by scott-gray** [comment]
You'll need this too:

```ng = NervanaGPU()```

You might also try some basic elementwise ops too if that works.  Something like this:
```
a = ng.empty((10, 10))
b = ng.empty((10, 1))
a[:] = ng.rand()
b[:] = ng.var(a, axis=1)
print b.get()```

**Comment by revilokeb** [comment]
Thanks for coming back to this.

Nothing running concurrently.

Your code snippets work as they should I guess:
![snippets](https://cloud.githubusercontent.com/assets/10588773/8557537/3fbcf86a-24fe-11e5-9e91-3c894a62b81a.png)

I suspect you are somehow right with pointing to PYTHONPATH. If I set  PYTHONPATH to /usr/local/lib/python2.7/dist-packages where my six 1.9.0 is located I get the above error. If settting PYTHONPATH to /usr/lib/python2.7/dist-packages  (six 1.5.2 from the dist) I am getting an AssertionError:

make test
Running unit tests...
nosetests -a '!slow' ""   nervanagpu
F
======================================================================
FAIL: nervanagpu.tests.test_tensor.TestTensor.test_math
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/revilokeb/nervanagpu/nervanagpu/tests/test_tensor.py", line 75, in test_math
    self.compare_helper('+', randA, randB, dtype)
  File "/home/revilokeb/nervanagpu/nervanagpu/tests/test_tensor.py", line 57, in compare_helper
    assert_tensor_near_equal(numpy_result, nervanaGPU_result, 1e-5)
  File "/home/revilokeb/nervanagpu/nervanagpu/util/testing.py", line 46, in assert_tensor_near_equal
    np.testing.assert_allclose(actual, desired, atol=tolerance, rtol=0)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0, atol=1e-05

(mismatch 100.0%)
 x: array([[ 0.79067934,  0.03362447,  1.27236915, ...,  1.88206363,
        -0.4193106 ,  0.06889164],
       [-0.66944927, -0.19951731,  0.84910023, ...,  1.56318402,...
 y: array([[ 0.79067934,  0.03362447,  1.27236915, ...,  1.88206363,
        -0.4193106 ,  0.06889164],
       [-0.66944927, -0.19951731,  0.84910023, ...,  1.56318402,...

----------------------------------------------------------------------
Ran 1 test in 0.244s

FAILED (failures=1)
make: *** [test] Error 1

**Comment by revilokeb** [comment]
I can now reproduce the error. I am using docker run -it --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidia1:/dev/nvidia1 kaixhin/nervanagpu-neon. Since nose is not installed, I am doing this (pip install nose) and then run make test in ~/nervanagpu which is giving me the very same error I have cited. 

Of course this is the same hardware that the docker now is running but a different install. Can anybody reproduce this or is it just my bizarre hardware?

**Comment by revilokeb** [comment]
Ok, I have run all CUDA 7 Samples again (flawlessly) and by some magic the problem has gone away, both locally and in docker. All the more, I can now use nervanagpu with neon and I am already on my way training alex / other nets. Sorry that I cannot really explain that error but thanks Nervana-Guys anyway!
