### ISSUE TITLE
Why K dim must be multiple of 8 for convolutional layers?

### ISSUE THREAD

**Issue by variousvirgil** [NervanaSystems/nervanagpu#20]
In [layers.py](https://github.com/NervanaSystems/nervanagpu/blob/e6392353cd6f9200868a7b17d7ab22c938de797e/nervanagpu/layers.py#L292), there is
```assert K % 8 == 0, "K dim must be multiple of 8"```

In fact, in my work, the final is a convolutional layer of 1 feature map so as to compute the euclidean loss and I'm stuck. Is there any solution to this problem? Thanks.

**Comment by scott-gray** [comment]
In fp32, K just needs to be a multiple of 4.  This is for performance reasons (vector loads are faster than single loads).  But you should just be able to mask your targets.  Set the first to the desired value, then fix the other 3 or 7 to zero.

**Comment by variousvirgil** [comment]
I see. Thank you for your quick response!
