### ISSUE TITLE
Question: any way I can pass a `cl_mem` to your library, and get the convolutions to run against that?

### ISSUE THREAD

**Issue by hughperkins** [NervanaSystems/nervanagpu#26]
Question: any way I can pass a `cl_mem` to your library, and get the convolutions to run against that?

Obviously, you'd probably need to do some driver-level hacking, possibly with the help of nvidia, to do this, in order to retrieve the appropriate `float *` from it somehow.  I cannot do this myself, because I dont want to expose myself to nvidia's IP, or vioalte any license agreements etc, but ... maybe.... you are able to do this???

Then I can make it that my variuos opencl libraries can use winograd on cuda gpus, and other libraries on non-cuda gpus.

**Comment by hughperkins** [comment]
(just to clarify: when I say 'the convolutions', I mean 'winograd convolution kernels')

**Comment by nervetumer** [comment]
this repo is deprecated.  please post on the neon repo for the winograd kernels https://github.com/NervanaSystems/neon

**Comment by hughperkins** [comment]
right, good point.  I think you should rename the repo or something though, I'm always selecting it by accident :-(
