### ISSUE TITLE
Install instructions for ubuntu.

### ISSUE THREAD

**Issue by Russell91** [NervanaSystems/nervanagpu#5]
Additional details that I needed to get the system working on Ubuntu 14.04 x64:

You will need cuda-7.0 (or possibly the latest release of cuda-6.5) to avoid an error about missing sm_52.
If you run make with sudo (which I had to), you need nvcc to be on your path when using sudo (see http://askubuntu.com/questions/428234/nvcc-not-found-but-only-when-using-sudo).
You will need to upgrade six.py (sudo pip install six --upgrade)
You will need python-dev (apt-get install python-dev)

After all of this I finally got `make kernels`, `make python`, and `make test` to pass. But I am still getting an issue when running the matrix multiplication example with the following stack trace:

    Traceback (most recent call last):
      File "a.py", line 23, in <module>
        ng.dot(devA.T, devB, devC, relu=False)
      File "/home/stewartr/git/nervanagpu/nervanagpu/nervanagpu.py", line 769, in dot
        kernel = _get_gemm_kernel(self.cubin_path, clss, op, size)
      File "<string>", line 2, in _get_gemm_kernel
      File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 423, in context_dependent_memoize
        result = func(*args)
      File "/home/stewartr/git/nervanagpu/nervanagpu/nervanagpu.py", line 1019, in _get_gemm_kernel
        module = _get_module(path, clss, op, size)
      File "<string>", line 2, in _get_module
      File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 423, in context_dependent_memoize
        result = func(*args)
      File "/home/stewartr/git/nervanagpu/nervanagpu/nervanagpu.py", line 1015, in _get_module
        return drv.module_from_file(os.path.join(path, cubin))
    pycuda._driver.LogicError: cuModuleLoad failed: invalid source

Output of pycuda.VERSION is (2014, 1) and print(os.path.join(path, cubin)) returns /home/stewartr/git/nervanagpu/nervanagpu/kernels/cubin/hgemm_tn_128x32.cubin. I do find it strange that it selected the x64 version. Replacing the x32 version with the x64 did not solve the issue though.

It seems that the root of the issue is that pycuda cannot load your provided cubin files. Any idea why this might be?

**Comment by scott-gray** [comment]
What GPU are you running this on?  If you're not running this on a maxwell card you'll need to use the cudanet backend.

**Comment by Russell91** [comment]
Oops, I specifically ran on my 780 TI instead of my k40 because I thought it was a Maxwell card, but it looks like it is not. That explains the error.

**Comment by scott-gray** [comment]
nervanagpu is maxwell only.  Cudanet has all the same functionality but built with cuda-convnet2 and cublas.  The elementwise is non-compounding unfortunately (I haven't had the time to get pycuda to play nice with cuda-convnet). But a $200 GTX 960 should still perform about as well as a K40 with nervanagpu.  And with fp16 you essentially double your available memory.

Another alternative is that you could with a bit of hacking get my elementwise working well with cuDNN/cublas.  See the cudnn.py and cublas.py scripts in the benchmark dir to see how those can be used from python.
